---
- name: Create Prometheus User and Group
  user:
    name: prometheus
    system: yes
    shell: /usr/sbin/nologin
    group: prometheus

- name: Create Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - /etc/prometheus
    - /var/lib/prometheus                                                                                                                                                                                                                                   - name: Download Prometheus                                                                                                     get_url:                                                                                                                        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz
    checksum: "sha256:{{ prometheus_checksum }}"

- name: Extract Prometheus
  unarchive:
    remote_src: yes
    src: /tmp/prometheus.tar.gz
    dest: /tmp
    owner: prometheus
    group: prometheus

- name: Install Prometheus Binaries
  copy:
    remote_src: yes
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: /usr/local/bin/{{ item }}
    owner: prometheus
    group: prometheus
    mode: 0755
  loop:
    - prometheus
    - promtool

- name: Install Prometheus Config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus

- name: Install systemd service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service

- name: Reload systemd and start Prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes

#haziq
- name: Clean up
  file:
    path: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64"
    state: absent
